apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: application-sample-other-4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-component-two
    app.kubernetes.io/part-of: application-sample-4
  name: application-sample-other-4
  namespace: application-service-system
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: application-sample-other-4
status:
  loadBalancer: {}
